# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'FRONT_END/package.json'
    versionSpec: '18.x'
    checkLatest: true
    force32bit: true
  scripts : 'npm run build'
