# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: default

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'BACK_END/pom.xml'

- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'C:\agent\_work\1\s\target\SI_RH_DSN.jar'
    MachineNames: '192.213.71.243'
    AdminUserName: 'Administrateur'
    AdminPassword: 'SdRh_SrV_App_2024'
    TargetPath: 'C:\Users\Administrateur.WIN-SGHEVTHFV84\Desktop\deployement\back_end'