package com.example.grh_n.security.user;

public enum PrivilegesEnum {

    // todo implment suppression total

    PRINT ,
    APPLICATION_TEXT_REGLEMENTAIRE ,
    APPLICATION_RECRUTEMENT ,
    APPLICATION_PAM ,
    APPLICATION_PAM_PAM ,
    APPLICATION_PAM_DASHBOARD ,
    APPLICATION_PAM_ETATS ,
    APPLICATION_PAM_PHOTO_EDITOR ,
    APPLICATION_PAM_NOTE ,
    APPLICATION_PAM_PAV,
    APPLICATION_SIMULATION ,
    APPLICATION_BUG_TRACKER ,
    NOTIFICATIONS ,
    HABILITAIONS_PROFILE_INFO ,
    GESTION_COMPTE ,
    OCR_RESULT_DIRECT_GRANT ,
    UPDATE_HABILITATION ,
    OCR_RESULT_PIN ,
    UPDATE_CONFIDENTIALITE ,
    UPLOAD ,
    ELASTIC_SEARCH ,
    OCR_MONITORING ,
    TEXT_REGLEMENTAIRE_PREF ,
    TEXT_REGLEMENTAIRE_PREF111111 ,
    PERSONNEL_NOTES_SEE_ALL ,

}
