drop sequence INS_REC_D_INSCRIPTION_SEQUENCE ;

CREATE SEQUENCE INS_REC_D_INSCRIPTION_SEQUENCE
    START WITH 1
    MAXVALUE 999999999999999999999999999
    MINVALUE 1
    increment by 10
    NOCYCLE
    CACHE 20
    NOORDER;

drop trigger INS_REC_D_INSCRIPTION ;

CREATE OR REPLACE TRIGGER INS_REC_D_INSCRIPTION
    BEFORE INSERT
    ON REC_D_INSCRIPTION
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := extract(year from sysdate) || INS_REC_D_INSCRIPTION_SEQUENCE.NEXTVAL;
    END IF;
END;

