export const UPLOAD_STATUS = {
  UPLOADING: "UPLOADING",
  NEW: "NEW",
  DONE_UPLOADING: "DONE_UPLOADING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  ALREADY_EXIST: "ALREADY_EXIST",
  NEED_EDITING: "NEED_EDITING",
};
